language: ruby
rvm:
- 2.1.2
env:
- DB=postgresql
script:
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake db:test:prepare
- bundle exec rake
before_script:
- cp config/database.travis.yml config/database.yml
- psql -c 'create database "flight-social-network_test"' -U postgres
deploy:
  provider: s3
  access_key_id: AKIAI3FKVY4NQOPA6J3A
  secret_access_key:
    secure: aN5jnr3E/99GHMiLiUyXIlPfNKDC7GIbO/HrPCwpnisanV6WAmEJ+ZI92TQJBQ2hhZ2yDZeIO60am1yQbebamzERj0APK9Fn4poRJVnm82c4E7KKODjq0opbvlLz5fwetcEsxLH4QLnTtnQS9uMpcaHKL5T+ZrhRvb26SLn+eAg=
  bucket: flight-dbc-network
  local-dir: 'no'
  upload-dir: 'no'
  acl: !ruby/string:HighLine::String public_read
  on:
    repo: simongondeck/flight-social-network
