# config/database.travis.yml

postgresql: &postgresql
  adapter: postgresql
  username: postgres
  password:
  database: flight-social-network_<%= Rails.env %>
  min_messages: ERROR

defaults: &defaults
  pool: 5
  timeout: 5000
  host: localhost
  <<: *<%= ENV['DB'] || "postgresql" %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
